SETTING:
  MODEL_DIR_NAME: '../models/' # 学習結果の諸々を保存するディレクトリ
  SUB_DIR_NAME: '../data/submission/' # 提出ファイル出力先ディレクトリ
  RAW_DATA_DIR_NAME: '../data/raw/' # オリジナルデータの格納先ディレクトリ
  FEATURE_DIR_NAME: '../data/features/' # 生成した特徴量格納ディレクトリ
  TRAIN_FILE_NAME: 'train.pkl' # 学習に使用するtrainファイル名
  TEST_FILE_NAME: 'test.pkl' # 予測対象のtestファイル名
  SLACK_NOTIFY: False
  TARGET_COL: 'target' # 目的変数のカラム名
  METRICS: 'mean_absolute_error' #[]
  CALC_SHAP: False # SHAPでの重要度を計算するか否か[True or False]
  SAVE_TRAIN_PRED: True # 学習データでの推論結果を保存するか否か[True or False]
  CV:
    method: 'StratifiedKFold' # [KFold, StratifiedKFold ,GroupKFold, StratifiedGroupKFold, CustomTimeSeriesSplitter, TrainTestSplit]から選択可能
    n_splits: 3 # k数
    random_state: 42 # seed
    shuffle: True # データをシャッフルするか否か
    cv_target_gr: 'chip_id' # GroupKFold or StratifiedGroupKFold の場合に対象とするカラム名を設定
    cv_target_sf: 'target' # StratifiedKFold or StratifiedGroupKFold の場合に対象とするカラム名を設定

MODEL_LGB:
  PARAM:
    objective: 'binary'
    metric: 'None'
    boosting: 'gbdt'
    lambda_l1: 1.2812997446158112
    lambda_l2: 0.04132762476340549
    num_leaves: 2
    feature_fraction: 0.8839999999999999
    bagging_fraction: 1.0
    bagging_freq: 0
    min_child_samples: 100
    verbose: -1
    num_round: 1000
    early_stopping_rounds: 100
    verbose_eval: 500
    bagging_seed: 42
    feature_fraction_seed: 42
    drop_seed: 42
    seed: 42

MODEL_CB:
  PARAM:
    loss_function: 'Logloss'
    eval_metric: 'AUC'
    learning_rate: 0.05
    iterations: 100 # 4000
    early_stopping_rounds: 100 # 400
    random_seed: 42
    verbose_eval: 100
    depth: 2 # 5
    pred_type: 'Classifier' # [Regressor / Classifier]

MODEL_XGB:
  PARAM:

MODEL_NN:
  PARAM:
