import sys
import os
import datetime
import yaml
import json
import collections as cl
import warnings
import fire
import traceback
from atm5_model_lgb import atm5_ModelLGB
# from m5_model_lgb import M5_ModelLGB
# from model_cb import ModelCB
# from model_nn import ModelNN
# from model_xgb import ModelXGB
from atm5_runner import atm5_Runner
from util import Submission

warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

# now = datetime.datetime.now()
# suffix = now.strftime("_%m%d_%H%M")
key_list = ['use_features', 'model_params', 'cv', 'setting']

CONFIG_FILE = '../configs/config.yaml'

with open(CONFIG_FILE) as file:
    yml = yaml.load(file)
MODEL_DIR_NAME = yml['SETTING']['MODEL_DIR_NAME']
FEATURE_DIR_NAME = yml['SETTING']['FEATURE_DIR_NAME']


def exist_check(path, run_name):
    """学習ファイルの存在チェックと実行確認
    """
    dir_list = []
    for d in os.listdir(path):
        dir_list.append(d.split('-')[-1])

    if run_name in dir_list:
        print('同名のrunが実行済みです。再実行しますか？[Y/n]')
        x = input('>> ')
        if x != 'Y':
            print('終了します')
            sys.exit(0)


def my_makedirs(path):
    """引数のpathディレクトリが存在しなければ、新規で作成する
    path:ディレクトリ名
    """
    if not os.path.isdir(path):
        os.makedirs(path)


def save_model_config(key_list, value_list, dir_name, run_name):
    """jsonファイル生成
    """
    ys = cl.OrderedDict()
    for i, v in enumerate(key_list):
        data = cl.OrderedDict()
        data = value_list[i]
        ys[v] = data

    fw = open(dir_name + run_name + '_param.json', 'w')
    json.dump(ys, fw, indent=4, default=set_default)


def set_default(obj):
    """json出力の際にset型のオブジェクトをリストに変更する
    """
    if isinstance(obj, set):
        return list(obj)
    raise TypeError


def main(mode='prd', create_features=True, model_type='lgb') -> str:

    # confirm('***** mode:{}, create_feature:{} '.format(str(mode), str(create_features)))

    now = datetime.datetime.now()
    suffix = now.strftime("_%m%d%H%M")

    # CVの設定.methodは[KFold, StratifiedKFold ,GroupKFold, StratifiedGroupKFold, CustomTimeSeriesSplitter, TrainTestSplit]から選択可能
    # CVしない場合（全データで学習させる場合）はmethodに'None'を設定
    # StratifiedKFold or GroupKFold or StratifiedGroupKFold の場合はcv_target_gr, cv_target_sfに対象カラム名を設定する
    # TrainTestSplitの場合はtest_sizeにtest setの割合を設定する

    # CustomTimeSeriesSplitterの例
    # cv = {
    #     'method': 'StratifiedKFold',
    #     'n_splits': 5,
    #     'random_state': 99,
    #     'shuffle': True,
    #     'cv_target': 'target'
    # }
    cv = {
        'method': 'StratifiedKFold',
        'n_splits': 5,
        'random_state': 42,
        'shuffle': True,
        'cv_target_gr': 'chip_id',
        'cv_target_sf': 'target'
    }

    # 学習・推論 LightGBM ###################################
    # run nameの設定
    run_name = 'lgb'
    run_name = run_name + '_' + cv.get('method') + suffix + 'cat_lgbm_pl45_55'
    dir_name = MODEL_DIR_NAME + run_name + '/'

    exist_check(MODEL_DIR_NAME, run_name)
    my_makedirs(dir_name)

    # 諸々の設定
    setting = {
        'run_name': run_name,  # run名
        'feature_directory': FEATURE_DIR_NAME,  # 特徴量の読み込み先ディレクトリ
        'target': 'target',  # 目的変数
        'calc_shap': False,  # shap値を計算するか否か
        'save_train_pred': True  # trainデータでの推論値を保存するか否か（trainデータでの推論値を特徴量として加えたい場合はTrueに設定する）
    }

    # optuna fold out
    model_params = {
        'objective': 'binary',
        'metric': 'None',
        'boosting': 'gbdt',
        'lambda_l1': 1.2812997446158112,
        'lambda_l2': 0.04132762476340549,
        'num_leaves': 2,
        'feature_fraction': 0.8839999999999999,
        'bagging_fraction': 1.0,
        'bagging_freq': 0,
        'min_child_samples': 100,
        'verbose': -1,
        'num_round': 4000,
        'early_stopping_rounds': 400,
        'verbose_eval': 200,
        'bagging_seed': 42,
        'feature_fraction_seed': 42,
        'drop_seed': 42,
        'seed': 42
    }

    features = [
        # 'chip_id',
        'exc_wl',
        # 'layout_a',
        # 'layout_x',
        # 'layout_y',
        'distance',
        'distance_x',
        'distance_y',
        'pos_x',
        'params0',
        'params1',
        'params2',
        'params3',
        'params4',
        'params5',
        'params6',
        # 'cavity_mean',
        # 'cavity_std',
        # 'cavity_median',
        # 'cavity_skew',
        # 'cavity_kurt',
        # 'diff_chip_id_mean_intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.8',
        # 'diff_chip_id_mean_intensity__ar_coefficient__coeff_2__k_10',
        # 'diff_chip_id_mean_intensity__fft_coefficient__attr_"abs"__coeff_65',
        # 'diff_chip_id_mean_intensity__fft_coefficient__attr_"abs"__coeff_72',
        # 'diff_chip_id_mean_params2_multi_params5',
        # 'diff_chip_id_mean_fwhm_mult_num_peak_086',
        # 'diff_chip_id_mean_intensity_max_divid_q80',
        # 'diff_chip_id_mean_dc_umap2',
        # 'diff_chip_id_mean_fwhm_mult_num_peak_088',
        # 'diff_chip_id_mean_params3_divid_params1',
        # 'diff_chip_id_mean_intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.6',
        # 'diff_chip_id_mean_params5_multi_params2',
        # 'diff_chip_id_mean_dc_tsne2',
        # 'diff_chip_id_mean_fwhm_mult_num_peak_084',
        # 'layout_type',
        # 'diff_layout_type_mean_params0',
        # 'diff_layout_type_mean_params1',
        # 'diff_layout_type_mean_params2',
        # 'diff_layout_type_mean_params3',
        # 'diff_layout_type_mean_params4',
        # 'diff_layout_type_mean_params5',
        # 'diff_layout_type_mean_params6',
        # 'diff_layout_type_mean_rms',
        # 'diff_layout_type_mean_beta',
        # 'diff_layout_type_mean_intensity_amplitude_v',
        # 'diff_layout_type_mean_intensity_max',
        # 'diff_layout_type_mean_intensity_min',
        # 'diff_layout_type_mean_intensity_q90',
        # 'diff_layout_type_mean_intensity_q75',
        # 'diff_layout_type_mean_fwhm_10',
        # 'diff_layout_type_mean_num_peak_10',
        # 'diff_layout_type_mean_fwhm_098',
        # 'diff_layout_type_mean_num_peak_098',
        # 'diff_layout_type_mean_fwhm_096',
        # 'diff_layout_type_mean_num_peak_096',
        # 'diff_layout_type_mean_fwhm_094',
        # 'diff_layout_type_mean_num_peak_094',
        # 'diff_layout_type_mean_fwhm_092',
        # 'diff_layout_type_mean_num_peak_092',
        # 'diff_layout_type_mean_fwhm_09',
        # 'diff_layout_type_mean_num_peak_09',
        # 'diff_layout_type_mean_fwhm_088',
        # 'diff_layout_type_mean_num_peak_088',
        # 'diff_layout_type_mean_fwhm_086',
        # 'diff_layout_type_mean_num_peak_086',
        # 'diff_layout_type_mean_fwhm_084',
        # 'diff_layout_type_mean_num_peak_084',
        # 'diff_layout_type_mean_fwhm_082',
        # 'diff_layout_type_mean_num_peak_082',
        # 'diff_layout_type_mean_fwhm_08',
        # 'diff_layout_type_mean_num_peak_08',
        # 'diff_layout_type_mean_fwhm_078',
        # 'diff_layout_type_mean_num_peak_078',
        # 'diff_layout_type_mean_fwhm_076',
        # 'diff_layout_type_mean_num_peak_076',
        # 'diff_layout_type_mean_fwhm_074',
        # 'diff_layout_type_mean_num_peak_074',
        # 'diff_layout_type_mean_fwhm_072',
        # 'diff_layout_type_mean_num_peak_072',
        # 'diff_layout_type_mean_fwhm_07',
        # 'diff_layout_type_mean_num_peak_07',
        # 'diff_layout_type_mean_fwhm_068',
        # 'diff_layout_type_mean_num_peak_068',
        # 'diff_layout_type_mean_fwhm_066',
        # 'diff_layout_type_mean_num_peak_066',
        # 'diff_layout_type_mean_fwhm_064',
        # 'diff_layout_type_mean_num_peak_064',
        # 'diff_layout_type_mean_fwhm_062',
        # 'diff_layout_type_mean_num_peak_062',
        # 'diff_layout_type_mean_fwhm_06',
        # 'diff_layout_type_mean_num_peak_06',
        # 'diff_layout_type_mean_fwhm_058',
        # 'diff_layout_type_mean_num_peak_058',
        # 'diff_layout_type_mean_fwhm_056',
        # 'diff_layout_type_mean_num_peak_056',
        # 'diff_layout_type_mean_fwhm_054',
        # 'diff_layout_type_mean_num_peak_054',
        # 'diff_layout_type_mean_fwhm_052',
        # 'diff_layout_type_mean_num_peak_052',
        # 'diff_layout_type_mean_fwhm_05',
        # 'diff_layout_type_mean_num_peak_05',
        # --- TODO: paramsの交互作用特徴量
        'params0_multi_rms',
        'params0_divid_rms',
        # 'params0_plus_rms',
        # 'params0_minus_rms',
        'params0_multi_beta',
        'params0_divid_beta',
        # 'params0_plus_beta',
        # 'params0_minus_beta',
        'params1_multi_rms',
        'params1_divid_rms',
        # 'params1_plus_rms',
        # 'params1_minus_rms',
        'params1_multi_beta',
        'params1_divid_beta',
        # 'params1_plus_beta',
        # 'params1_minus_beta',
        'params2_multi_rms',
        'params2_divid_rms',
        # 'params2_plus_rms',
        # 'params2_minus_rms',
        'params2_multi_beta',
        'params2_divid_beta',
        # 'params2_plus_beta',
        # 'params2_minus_beta',
        'params3_multi_rms',
        'params3_divid_rms',
        # 'params3_plus_rms',
        # 'params3_minus_rms',
        'params3_multi_beta',
        'params3_divid_beta',
        # 'params3_plus_beta',
        # 'params3_minus_beta',
        'params4_multi_rms',
        'params4_divid_rms',
        # 'params4_plus_rms',
        # 'params4_minus_rms',
        'params4_multi_beta',
        'params4_divid_beta',
        # 'params4_plus_beta',
        # 'params4_minus_beta',
        'params5_multi_rms',
        'params5_divid_rms',
        # 'params5_plus_rms',
        # 'params5_minus_rms',
        'params5_multi_beta',
        'params5_divid_beta',
        # 'params5_plus_beta',
        # 'params5_minus_beta',
        'params6_multi_rms',
        'params6_divid_rms',
        # 'params6_plus_rms',
        # 'params6_minus_rms',
        'params6_multi_beta',
        'params6_divid_beta',
        # 'params6_plus_beta',
        # 'params6_minus_beta',
        'params0_multi_params1',
        'params0_divid_params1',
        # 'params0_plus_params1',
        # 'params0_minus_params1',
        # 'params0_absminus_params1',
        'params0_multi_params2',
        'params0_divid_params2',
        # 'params0_plus_params2',
        # 'params0_minus_params2',
        # 'params0_absminus_params2',
        'params0_multi_params3',
        'params0_divid_params3',
        # 'params0_plus_params3',
        # 'params0_minus_params3',
        # 'params0_absminus_params3',
        'params0_multi_params4',
        'params0_divid_params4',
        # 'params0_plus_params4',
        # 'params0_minus_params4',
        # 'params0_absminus_params4',
        'params0_multi_params5',
        'params0_divid_params5',
        # 'params0_plus_params5',
        # 'params0_minus_params5',
        # 'params0_absminus_params5',
        'params0_multi_params6',
        'params0_divid_params6',
        # 'params0_plus_params6',
        # 'params0_minus_params6',
        # 'params0_absminus_params6',
        'params1_multi_params0',
        'params1_divid_params0',
        # 'params1_plus_params0',
        # 'params1_minus_params0',
        'params1_multi_params2',
        'params1_divid_params2',
        # 'params1_plus_params2',
        # 'params1_minus_params2',
        # 'params1_absminus_params2',
        'params1_multi_params3',
        'params1_divid_params3',
        # 'params1_plus_params3',
        # 'params1_minus_params3',
        # 'params1_absminus_params3',
        'params1_multi_params4',
        'params1_divid_params4',
        # 'params1_plus_params4',
        # 'params1_minus_params4',
        # 'params1_absminus_params4',
        'params1_multi_params5',
        'params1_divid_params5',
        # 'params1_plus_params5',
        # 'params1_minus_params5',
        # 'params1_absminus_params5',
        'params1_multi_params6',
        'params1_divid_params6',
        # 'params1_plus_params6',
        # 'params1_minus_params6',
        # 'params1_absminus_params6',
        'params2_multi_params0',
        'params2_divid_params0',
        # 'params2_plus_params0',
        # 'params2_minus_params0',
        'params2_multi_params1',
        'params2_divid_params1',
        # 'params2_plus_params1',
        # 'params2_minus_params1',
        'params2_multi_params3',
        'params2_divid_params3',
        # 'params2_plus_params3',
        # 'params2_minus_params3',
        # 'params2_absminus_params3',
        'params2_multi_params4',
        'params2_divid_params4',
        # 'params2_plus_params4',
        # 'params2_minus_params4',
        # 'params2_absminus_params4',
        'params2_multi_params5',
        'params2_divid_params5',
        # 'params2_plus_params5',
        # 'params2_minus_params5',
        # 'params2_absminus_params5',
        'params2_multi_params6',
        'params2_divid_params6',
        # 'params2_plus_params6',
        # 'params2_minus_params6',
        # 'params2_absminus_params6',
        'params3_multi_params0',
        'params3_divid_params0',
        # 'params3_plus_params0',
        # 'params3_minus_params0',
        'params3_multi_params1',
        'params3_divid_params1',
        # 'params3_plus_params1',
        # 'params3_minus_params1',
        'params3_multi_params2',
        'params3_divid_params2',
        # 'params3_plus_params2',
        # 'params3_minus_params2',
        'params3_multi_params4',
        'params3_divid_params4',
        # 'params3_plus_params4',
        # 'params3_minus_params4',
        # 'params3_absminus_params4',
        'params3_multi_params5',
        'params3_divid_params5',
        # 'params3_plus_params5',
        # 'params3_minus_params5',
        # 'params3_absminus_params5',
        'params3_multi_params6',
        'params3_divid_params6',
        # 'params3_plus_params6',
        # 'params3_minus_params6',
        # 'params3_absminus_params6',
        'params4_multi_params0',
        'params4_divid_params0',
        # 'params4_plus_params0',
        # 'params4_minus_params0',
        'params4_multi_params1',
        'params4_divid_params1',
        # 'params4_plus_params1',
        # 'params4_minus_params1',
        'params4_multi_params2',
        'params4_divid_params2',
        # 'params4_plus_params2',
        # 'params4_minus_params2',
        'params4_multi_params3',
        'params4_divid_params3',
        # 'params4_plus_params3',
        # 'params4_minus_params3',
        'params4_multi_params5',
        'params4_divid_params5',
        # 'params4_plus_params5',
        # 'params4_minus_params5',
        # 'params4_absminus_params5',
        'params4_multi_params6',
        'params4_divid_params6',
        # 'params4_plus_params6',
        # 'params4_minus_params6',
        # 'params4_absminus_params6',
        'params5_multi_params0',
        'params5_divid_params0',
        # 'params5_plus_params0',
        # 'params5_minus_params0',
        'params5_multi_params1',
        'params5_divid_params1',
        # 'params5_plus_params1',
        # 'params5_minus_params1',
        'params5_multi_params2',
        'params5_divid_params2',
        # 'params5_plus_params2',
        # 'params5_minus_params2',
        'params5_multi_params3',
        'params5_divid_params3',
        # 'params5_plus_params3',
        # 'params5_minus_params3',
        'params5_multi_params4',
        'params5_divid_params4',
        # 'params5_plus_params4',
        # 'params5_minus_params4',
        'params5_multi_params6',
        'params5_divid_params6',
        # 'params5_plus_params6',
        # 'params5_minus_params6',
        # 'params5_absminus_params6',
        'params6_multi_params0',
        'params6_divid_params0',
        # 'params6_plus_params0',
        # 'params6_minus_params0',
        'params6_multi_params1',
        'params6_divid_params1',
        # 'params6_plus_params1',
        # 'params6_minus_params1',
        'params6_multi_params2',
        'params6_divid_params2',
        # 'params6_plus_params2',
        # 'params6_minus_params2',
        'params6_multi_params3',
        'params6_divid_params3',
        # 'params6_plus_params3',
        # 'params6_minus_params3',
        'params6_multi_params4',
        'params6_divid_params4',
        # 'params6_plus_params4',
        # 'params6_minus_params4',
        'params6_multi_params5',
        'params6_divid_params5',
        # 'params6_plus_params5',
        # 'params6_minus_params5',
        'rms',
        'beta',
        # --- TODO: スペクトル波長データ
        'intensity_max',
        'intensity_min',
        'intensity_mean',
        'intensity_std',
        'intensity_sum',
        'intensity_median',
        'intensity_amplitude_v',
        # 'intensity_max_log1p',
        # 'intensity_mean_log1p',
        # 'intensity_std_log1p',
        # 'intensity_sum_log1p',
        # 'intensity_median_log1p',
        # 'intensity_amplitude_v_log1p',
        'intensity_q10',
        'intensity_q25',
        'intensity_q50',
        'intensity_q75',
        'intensity_q80',
        'intensity_q85',
        'intensity_q90',
        'intensity_max_minus_q90',
        'intensity_max_minus_q85',
        'intensity_max_minus_q80',
        'intensity_max_minus_q75',
        'intensity_max_minus_q50',
        'intensity_max_multi_q90',
        'intensity_max_multi_q85',
        'intensity_max_multi_q80',
        'intensity_max_multi_q75',
        'intensity_max_multi_q50',
        'intensity_max_divid_q90',
        'intensity_max_divid_q85',
        'intensity_max_divid_q80',
        'intensity_max_divid_q75',
        'intensity_max_divid_q50',
        'intensity_q85_divid_q90',
        'intensity_q80_divid_q90',
        'intensity_q75_divid_q90',
        'intensity_q50_divid_q90',
        # --- ピーク&半値幅のデータ
        'fwhm_09',
        # 'num_peak_09',
        'fwhm_088',
        # 'num_peak_088',
        'fwhm_086',
        # 'num_peak_086',
        'fwhm_084',
        # 'num_peak_084',
        'fwhm_082',
        # 'num_peak_082',
        'fwhm_08',
        # 'num_peak_08',
        'fwhm_078',
        # 'num_peak_078',
        'fwhm_076',
        # 'num_peak_076',
        'fwhm_074',
        # 'num_peak_074',
        'fwhm_072',
        # 'num_peak_072',
        'fwhm_07',
        # 'num_peak_07',
        'fwhm_068',
        # 'num_peak_068',
        'fwhm_066',
        # 'num_peak_066',
        'fwhm_064',
        # 'num_peak_064',
        'fwhm_062',
        # 'num_peak_062',
        'fwhm_06',
        # 'num_peak_06',
        'fwhm_058',
        # 'num_peak_058',
        'fwhm_056',
        # 'num_peak_056',
        'fwhm_054',
        # 'num_peak_054',
        'fwhm_052',
        # 'num_peak_052',
        'fwhm_05',
        # 'num_peak_05',
        'fwhm_divid_num_peak_09',
        'fwhm_mult_num_peak_09',
        'fwhm_divid_num_peak_088',
        'fwhm_mult_num_peak_088',
        'fwhm_divid_num_peak_086',
        'fwhm_mult_num_peak_086',
        'fwhm_divid_num_peak_084',
        'fwhm_mult_num_peak_084',
        'fwhm_divid_num_peak_082',
        'fwhm_mult_num_peak_082',
        'fwhm_divid_num_peak_08',
        'fwhm_mult_num_peak_08',
        'fwhm_divid_num_peak_078',
        'fwhm_mult_num_peak_078',
        'fwhm_divid_num_peak_076',
        'fwhm_mult_num_peak_076',
        'fwhm_divid_num_peak_074',
        'fwhm_mult_num_peak_074',
        'fwhm_divid_num_peak_072',
        'fwhm_mult_num_peak_072',
        'fwhm_divid_num_peak_07',
        'fwhm_mult_num_peak_07',
        # 'fwhm_divid_num_peak_068',
        # 'fwhm_mult_num_peak_068',
        # 'fwhm_divid_num_peak_066',
        # 'fwhm_mult_num_peak_066',
        # 'fwhm_divid_num_peak_064',
        # 'fwhm_mult_num_peak_064',
        # 'fwhm_divid_num_peak_062',
        # 'fwhm_mult_num_peak_062',
        # 'fwhm_divid_num_peak_06',
        # 'fwhm_mult_num_peak_06',
        # 'fwhm_divid_num_peak_058',
        # 'fwhm_mult_num_peak_058',
        # 'fwhm_divid_num_peak_056',
        # 'fwhm_mult_num_peak_056',
        # 'fwhm_divid_num_peak_054',
        # 'fwhm_mult_num_peak_054',
        # 'fwhm_divid_num_peak_052',
        # 'fwhm_mult_num_peak_052',
        # 'fwhm_divid_num_peak_05',
        # 'fwhm_mult_num_peak_05',
        # --- TODO: 波形の圧縮データ
        'dc_umap1',
        'dc_umap2',
        'dc_tsne1',
        'dc_tsne2',
        # --- TODO: カテゴリごとの平均値と自身との差分
        # 'diff_chip_id_mean_params0',
        # 'diff_chip_id_mean_params1',
        # 'diff_chip_id_mean_params2',
        # 'diff_chip_id_mean_params3',
        # 'diff_chip_id_mean_params4',
        # 'diff_chip_id_mean_params5',
        # 'diff_chip_id_mean_params6',
        # 'diff_chip_id_mean_rms',
        # 'diff_chip_id_mean_beta',
        # 'diff_chip_id_mean_intensity_amplitude_v',
        # 'diff_chip_id_mean_fwhm_09',
        # # 'diff_chip_id_mean_num_peak_09',
        # 'diff_chip_id_mean_fwhm_088',
        # # 'diff_chip_id_mean_num_peak_088',
        # 'diff_chip_id_mean_fwhm_086',
        # # 'diff_chip_id_mean_num_peak_086',
        # 'diff_chip_id_mean_fwhm_084',
        # # 'diff_chip_id_mean_num_peak_084',
        # 'diff_chip_id_mean_fwhm_082',
        # # 'diff_chip_id_mean_num_peak_082',
        # 'diff_chip_id_mean_fwhm_08',
        # # 'diff_chip_id_mean_num_peak_08',
        # 'diff_chip_id_mean_fwhm_078',
        # # 'diff_chip_id_mean_num_peak_078',
        # 'diff_chip_id_mean_fwhm_076',
        # # 'diff_chip_id_mean_num_peak_076',
        # 'diff_chip_id_mean_fwhm_074',
        # # 'diff_chip_id_mean_num_peak_074',
        # 'diff_chip_id_mean_fwhm_072',
        # # 'diff_chip_id_mean_num_peak_072',
        # 'diff_chip_id_mean_fwhm_07',
        # # 'diff_chip_id_mean_num_peak_07',
        # 'diff_chip_id_mean_fwhm_068',
        # # 'diff_chip_id_mean_num_peak_068',
        # 'diff_chip_id_mean_fwhm_066',
        # # 'diff_chip_id_mean_num_peak_066',
        # 'diff_chip_id_mean_fwhm_064',
        # # 'diff_chip_id_mean_num_peak_064',
        # 'diff_chip_id_mean_fwhm_062',
        # # 'diff_chip_id_mean_num_peak_062',
        # 'diff_chip_id_mean_fwhm_06',
        # # 'diff_chip_id_mean_num_peak_06',
        # 'diff_chip_id_mean_fwhm_058',
        # # 'diff_chip_id_mean_num_peak_058',
        # 'diff_chip_id_mean_fwhm_056',
        # # 'diff_chip_id_mean_num_peak_056',
        # 'diff_chip_id_mean_fwhm_054',
        # # 'diff_chip_id_mean_num_peak_054',
        # 'diff_chip_id_mean_fwhm_052',
        # # 'diff_chip_id_mean_num_peak_052',
        # 'diff_chip_id_mean_fwhm_05',
        # # 'diff_chip_id_mean_num_peak_05',
        # # 'diff_chip_id_mean_intensity_max',
        # # 'diff_chip_id_mean_intensity_min',
        # # 'diff_chip_id_mean_intensity_q90',
        # # 'diff_chip_id_mean_intensity_q75',
        'diff_exc_wl_mean_params0',
        'diff_exc_wl_mean_params1',
        'diff_exc_wl_mean_params2',
        'diff_exc_wl_mean_params3',
        'diff_exc_wl_mean_params4',
        'diff_exc_wl_mean_params5',
        'diff_exc_wl_mean_params6',
        'diff_exc_wl_mean_rms',
        'diff_exc_wl_mean_beta',
        'diff_exc_wl_mean_intensity_amplitude_v',
        'diff_exc_wl_mean_fwhm_09',
        # 'diff_exc_wl_mean_num_peak_09',
        'diff_exc_wl_mean_fwhm_088',
        # 'diff_exc_wl_mean_num_peak_088',
        'diff_exc_wl_mean_fwhm_086',
        # 'diff_exc_wl_mean_num_peak_086',
        'diff_exc_wl_mean_fwhm_084',
        # 'diff_exc_wl_mean_num_peak_084',
        'diff_exc_wl_mean_fwhm_082',
        # 'diff_exc_wl_mean_num_peak_082',
        'diff_exc_wl_mean_fwhm_08',
        # 'diff_exc_wl_mean_num_peak_08',
        'diff_exc_wl_mean_fwhm_078',
        # 'diff_exc_wl_mean_num_peak_078',
        'diff_exc_wl_mean_fwhm_076',
        # 'diff_exc_wl_mean_num_peak_076',
        'diff_exc_wl_mean_fwhm_074',
        # 'diff_exc_wl_mean_num_peak_074',
        'diff_exc_wl_mean_fwhm_072',
        # 'diff_exc_wl_mean_num_peak_072',
        'diff_exc_wl_mean_fwhm_07',
        # 'diff_exc_wl_mean_num_peak_07',
        'diff_exc_wl_mean_fwhm_068',
        # 'diff_exc_wl_mean_num_peak_068',
        'diff_exc_wl_mean_fwhm_066',
        # 'diff_exc_wl_mean_num_peak_066',
        'diff_exc_wl_mean_fwhm_064',
        # 'diff_exc_wl_mean_num_peak_064',
        'diff_exc_wl_mean_fwhm_062',
        # 'diff_exc_wl_mean_num_peak_062',
        'diff_exc_wl_mean_fwhm_06',
        # 'diff_exc_wl_mean_num_peak_06',
        'diff_exc_wl_mean_fwhm_058',
        # 'diff_exc_wl_mean_num_peak_058',
        'diff_exc_wl_mean_fwhm_056',
        # 'diff_exc_wl_mean_num_peak_056',
        'diff_exc_wl_mean_fwhm_054',
        # 'diff_exc_wl_mean_num_peak_054',
        'diff_exc_wl_mean_fwhm_052',
        # 'diff_exc_wl_mean_num_peak_052',
        'diff_exc_wl_mean_fwhm_05',
        # 'diff_exc_wl_mean_num_peak_05',
        # 'diff_exc_wl_mean_intensity_max',
        # 'diff_exc_wl_mean_intensity_min',
        # 'diff_exc_wl_mean_intensity_q90',
        # 'diff_exc_wl_mean_intensity_q75',
        # 'diff_layout_a_mean_params0',
        # 'diff_layout_a_mean_params1',
        # 'diff_layout_a_mean_params2',
        # 'diff_layout_a_mean_params3',
        # 'diff_layout_a_mean_params4',
        # 'diff_layout_a_mean_params5',
        # 'diff_layout_a_mean_params6',
        # 'diff_layout_a_mean_rms',
        # 'diff_layout_a_mean_beta',
        # 'diff_layout_a_mean_intensity_amplitude_v',
        # 'diff_layout_a_mean_fwhm_09',
        # # 'diff_layout_a_mean_num_peak_09',
        # 'diff_layout_a_mean_fwhm_088',
        # # 'diff_layout_a_mean_num_peak_088',
        # 'diff_layout_a_mean_fwhm_086',
        # # 'diff_layout_a_mean_num_peak_086',
        # 'diff_layout_a_mean_fwhm_084',
        # # 'diff_layout_a_mean_num_peak_084',
        # 'diff_layout_a_mean_fwhm_082',
        # # 'diff_layout_a_mean_num_peak_082',
        # 'diff_layout_a_mean_fwhm_08',
        # # 'diff_layout_a_mean_num_peak_08',
        # 'diff_layout_a_mean_fwhm_078',
        # # 'diff_layout_a_mean_num_peak_078',
        # 'diff_layout_a_mean_fwhm_076',
        # # 'diff_layout_a_mean_num_peak_076',
        # 'diff_layout_a_mean_fwhm_074',
        # # 'diff_layout_a_mean_num_peak_074',
        # 'diff_layout_a_mean_fwhm_072',
        # # 'diff_layout_a_mean_num_peak_072',
        # 'diff_layout_a_mean_fwhm_07',
        # # 'diff_layout_a_mean_num_peak_07',
        # 'diff_layout_a_mean_fwhm_068',
        # # 'diff_layout_a_mean_num_peak_068',
        # 'diff_layout_a_mean_fwhm_066',
        # # 'diff_layout_a_mean_num_peak_066',
        # 'diff_layout_a_mean_fwhm_064',
        # # 'diff_layout_a_mean_num_peak_064',
        # 'diff_layout_a_mean_fwhm_062',
        # # 'diff_layout_a_mean_num_peak_062',
        # 'diff_layout_a_mean_fwhm_06',
        # # 'diff_layout_a_mean_num_peak_06',
        # 'diff_layout_a_mean_fwhm_058',
        # # 'diff_layout_a_mean_num_peak_058',
        # 'diff_layout_a_mean_fwhm_056',
        # # 'diff_layout_a_mean_num_peak_056',
        # 'diff_layout_a_mean_fwhm_054',
        # # 'diff_layout_a_mean_num_peak_054',
        # 'diff_layout_a_mean_fwhm_052',
        # # 'diff_layout_a_mean_num_peak_052',
        # 'diff_layout_a_mean_fwhm_05',
        # # 'diff_layout_a_mean_num_peak_05',
        # # 'diff_layout_a_mean_intensity_max',
        # # 'diff_layout_a_mean_intensity_min',
        # # 'diff_layout_a_mean_intensity_q90',
        # # 'diff_layout_a_mean_intensity_q75',
        # --- TODO: tsfreshで生成した特徴
        'intensity__ratio_beyond_r_sigma__r_10',
        'intensity__ar_coefficient__coeff_2__k_10',
        'intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.8',
        'intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.6',
        'intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.4',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.8',
        'intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.2',
        'intensity__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.0',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.6',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.4',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.0',
        'intensity__cid_ce__normalize_False',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.2',
        'intensity__fft_coefficient__attr_"abs"__coeff_55',
        'intensity__fft_coefficient__attr_"abs"__coeff_56',
        'intensity__large_standard_deviation__r_0.1',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"var"',
        'intensity__fft_coefficient__attr_"abs"__coeff_64',
        'intensity__fft_coefficient__attr_"abs"__coeff_57',
        'intensity__fft_coefficient__attr_"abs"__coeff_51',
        'intensity__fft_coefficient__attr_"abs"__coeff_52',
        'intensity__fft_coefficient__attr_"abs"__coeff_66',
        'intensity__fft_coefficient__attr_"abs"__coeff_68',
        'intensity__fft_coefficient__attr_"abs"__coeff_59',
        'intensity__fft_coefficient__attr_"abs"__coeff_61',
        'intensity__fft_coefficient__attr_"abs"__coeff_53',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.8',
        'intensity__fft_coefficient__attr_"abs"__coeff_54',
        'intensity__fft_coefficient__attr_"abs"__coeff_65',
        'intensity__partial_autocorrelation__lag_2',
        'intensity__fft_coefficient__attr_"abs"__coeff_63',
        'intensity__fft_coefficient__attr_"abs"__coeff_62',
        'intensity__fft_coefficient__attr_"abs"__coeff_71',
        'intensity__ar_coefficient__coeff_1__k_10',
        'intensity__fft_coefficient__attr_"abs"__coeff_50',
        'intensity__fft_coefficient__attr_"abs"__coeff_49',
        'intensity__fft_coefficient__attr_"abs"__coeff_48',
        'intensity__fft_coefficient__attr_"abs"__coeff_58',
        'intensity__fft_coefficient__attr_"abs"__coeff_46',
        'intensity__fft_coefficient__attr_"abs"__coeff_69',
        'intensity__fft_coefficient__attr_"abs"__coeff_67',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.6',
        'intensity__fft_coefficient__attr_"abs"__coeff_47',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"max"',
        'intensity__fft_coefficient__attr_"abs"__coeff_60',
        'intensity__fft_coefficient__attr_"abs"__coeff_80',
        'intensity__fft_coefficient__attr_"abs"__coeff_72',
        'intensity__fft_coefficient__attr_"abs"__coeff_76',
        'intensity__binned_entropy__max_bins_10',
        'intensity__fft_coefficient__attr_"abs"__coeff_70',
        'intensity__fft_coefficient__attr_"abs"__coeff_79',
        'intensity__ar_coefficient__coeff_3__k_10',
        'intensity__fft_coefficient__attr_"abs"__coeff_44',
        'intensity__fft_coefficient__attr_"abs"__coeff_78',
        'intensity__fft_coefficient__attr_"abs"__coeff_74',
        'intensity__fft_coefficient__attr_"abs"__coeff_77',
        'intensity__fft_coefficient__attr_"abs"__coeff_45',
        'intensity__maximum',
        'intensity__fft_coefficient__attr_"abs"__coeff_81',
        'intensity__fft_coefficient__attr_"abs"__coeff_75',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"var"',
        'intensity__fft_coefficient__attr_"abs"__coeff_43',
        'intensity__fft_coefficient__attr_"abs"__coeff_83',
        'intensity__fft_coefficient__attr_"abs"__coeff_40',
        'intensity__fft_coefficient__attr_"abs"__coeff_82',
        'intensity__fft_coefficient__attr_"abs"__coeff_73',
        'intensity__fft_coefficient__attr_"abs"__coeff_42',
        'intensity__fft_coefficient__attr_"abs"__coeff_41',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"max"',
        'intensity__fft_coefficient__attr_"abs"__coeff_36',
        'intensity__fft_coefficient__attr_"abs"__coeff_86',
        'intensity__fft_coefficient__attr_"abs"__coeff_39',
        'intensity__fft_coefficient__attr_"abs"__coeff_87',
        'intensity__index_mass_quantile__q_0.2',
        'intensity__fft_coefficient__attr_"abs"__coeff_84',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_2',
        'intensity__mean_abs_change',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.0',
        'intensity__absolute_sum_of_changes',
        'intensity__fft_aggregated__aggtype_"kurtosis"',
        'intensity__fft_aggregated__aggtype_"variance"',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_1',
        'intensity__fft_coefficient__attr_"abs"__coeff_38',
        'intensity__index_mass_quantile__q_0.3',
        'intensity__fft_coefficient__attr_"abs"__coeff_37',
        'intensity__fft_coefficient__attr_"abs"__coeff_85',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"max"',
        'intensity__fft_coefficient__attr_"abs"__coeff_90',
        'intensity__fft_coefficient__attr_"abs"__coeff_88',
        'intensity__fft_coefficient__attr_"abs"__coeff_92',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.2',
        'intensity__fft_coefficient__attr_"abs"__coeff_94',
        'intensity__fft_coefficient__attr_"abs"__coeff_89',
        'intensity__fft_coefficient__attr_"abs"__coeff_93',
        'intensity__fft_coefficient__attr_"abs"__coeff_35',
        'intensity__kurtosis',
        'intensity__skewness',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"var"',
        'intensity__fft_coefficient__attr_"abs"__coeff_97',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_3',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_0',
        'intensity__spkt_welch_density__coeff_2',
        'intensity__fft_coefficient__attr_"abs"__coeff_34',
        'intensity__index_mass_quantile__q_0.4',
        'intensity__partial_autocorrelation__lag_5',
        'intensity__index_mass_quantile__q_0.1',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"var"',
        'intensity__ratio_beyond_r_sigma__r_0.5',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"max"',
        'intensity__fft_coefficient__attr_"abs"__coeff_95',
        'intensity__partial_autocorrelation__lag_6',
        'intensity__approximate_entropy__m_2__r_0.9',
        'intensity__count_below_mean',
        'intensity__count_above_mean',
        'intensity__fft_coefficient__attr_"abs"__coeff_91',
        'intensity__approximate_entropy__m_2__r_0.7',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"max"',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"var"',
        'intensity__approximate_entropy__m_2__r_0.5',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"max"',
        'intensity__sample_entropy',
        'intensity__approximate_entropy__m_2__r_0.3',
        'intensity__fft_coefficient__attr_"abs"__coeff_96',
        'intensity__fft_coefficient__attr_"imag"__coeff_1',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"mean"',
        'intensity__linear_trend__attr_"stderr"',
        'intensity__linear_trend__attr_"slope"',
        'intensity__fft_coefficient__attr_"abs"__coeff_4',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"max"',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"mean"',
        'intensity__fft_coefficient__attr_"abs"__coeff_33',
        'intensity__first_location_of_maximum',
        'intensity__last_location_of_maximum',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"var"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"mean"',
        'intensity__fft_coefficient__attr_"abs"__coeff_3',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"mean"',
        'intensity__fft_coefficient__attr_"abs"__coeff_32',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"mean"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"mean"',
        'intensity__standard_deviation',
        'intensity__variance',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"max"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"min"',
        'intensity__linear_trend__attr_"rvalue"',
        'intensity__fft_coefficient__attr_"abs"__coeff_6',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"min"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"mean"',
        'intensity__fft_coefficient__attr_"abs"__coeff_2',
        'intensity__fft_coefficient__attr_"abs"__coeff_99',
        'intensity__augmented_dickey_fuller__attr_"usedlag"__autolag_"AIC"',
        'intensity__spkt_welch_density__coeff_5',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"min"',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"var"',
        'intensity__fft_coefficient__attr_"abs"__coeff_31',
        'intensity__fft_coefficient__attr_"abs"__coeff_5',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"mean"',
        'intensity__c3__lag_1',
        'intensity__fft_coefficient__attr_"abs"__coeff_7',
        'intensity__fft_coefficient__attr_"abs"__coeff_8',
        'intensity__fft_coefficient__attr_"abs"__coeff_30',
        'intensity__fft_coefficient__attr_"abs"__coeff_9',
        'intensity__fft_coefficient__attr_"abs"__coeff_98',
        'intensity__ar_coefficient__coeff_7__k_10',
        'intensity__ratio_beyond_r_sigma__r_7',
        'intensity__ar_coefficient__coeff_6__k_10',
        'intensity__fft_coefficient__attr_"abs"__coeff_29',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
        'intensity__fft_coefficient__attr_"abs"__coeff_1',
        'intensity__variation_coefficient',
        'intensity__fft_coefficient__attr_"abs"__coeff_10',
        'intensity__max_langevin_fixed_point__m_3__r_30',
        'intensity__c3__lag_2',
        'intensity__spkt_welch_density__coeff_8',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_8',
        'intensity__abs_energy',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"min"',
        'intensity__c3__lag_3',
        'intensity__fft_coefficient__attr_"abs"__coeff_11',
        'intensity__ratio_beyond_r_sigma__r_1',
        'intensity__fft_coefficient__attr_"abs"__coeff_13',
        'intensity__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"min"',
        'intensity__fft_coefficient__attr_"real"__coeff_1',
        'intensity__index_mass_quantile__q_0.6',
        'intensity__fft_coefficient__attr_"abs"__coeff_27',
        'intensity__partial_autocorrelation__lag_7',
        'intensity__fft_coefficient__attr_"abs"__coeff_12',
        'intensity__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"min"',
        'intensity__linear_trend__attr_"pvalue"',
        'intensity__fft_coefficient__attr_"abs"__coeff_28',
        'intensity__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"min"',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
        'intensity__fft_coefficient__attr_"abs"__coeff_15',
        'intensity__fft_coefficient__attr_"abs"__coeff_25',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"min"',
        'intensity__linear_trend__attr_"intercept"',
        'intensity__fft_coefficient__attr_"abs"__coeff_14',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
        'intensity__fft_aggregated__aggtype_"skew"',
        'intensity__fft_coefficient__attr_"abs"__coeff_16',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
        'intensity__partial_autocorrelation__lag_4',
        'intensity__fft_coefficient__attr_"abs"__coeff_26',
        'intensity__fft_coefficient__attr_"angle"__coeff_1',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"max"',
        'intensity__fft_coefficient__attr_"abs"__coeff_17',
        'intensity__index_mass_quantile__q_0.9',
        'intensity__fft_coefficient__attr_"abs"__coeff_24',
        'intensity__fft_coefficient__attr_"abs"__coeff_18',
        'intensity__longest_strike_above_mean',
        'intensity__fft_aggregated__aggtype_"centroid"',
        'intensity__longest_strike_below_mean',
        'intensity__approximate_entropy__m_2__r_0.1',
        'intensity__fft_coefficient__attr_"abs"__coeff_22',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"mean"',
        'intensity__fft_coefficient__attr_"abs"__coeff_23',
        'intensity__cwt_coefficients__coeff_5__w_5__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_4__w_5__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_6__w_5__widths_(2, 5, 10, 20)',
        'intensity__sum_of_reoccurring_data_points',
        'intensity__partial_autocorrelation__lag_1',
        'intensity__autocorrelation__lag_1',
        'intensity__ar_coefficient__coeff_8__k_10',
        'intensity__fft_coefficient__attr_"imag"__coeff_7',
        'intensity__cwt_coefficients__coeff_3__w_5__widths_(2, 5, 10, 20)',
        'intensity__sum_of_reoccurring_values',
        'intensity__fft_coefficient__attr_"abs"__coeff_20',
        'intensity__fft_coefficient__attr_"abs"__coeff_19',
        'intensity__ar_coefficient__coeff_4__k_10',
        'intensity__cid_ce__normalize_True',
        'intensity__fft_coefficient__attr_"abs"__coeff_21',
        'intensity__cwt_coefficients__coeff_7__w_5__widths_(2, 5, 10, 20)',
        'intensity__energy_ratio_by_chunks__num_segments_10__segment_focus_4',
        'intensity__friedrich_coefficients__coeff_3__m_3__r_30',
        'intensity__ar_coefficient__coeff_10__k_10',
        'intensity__index_mass_quantile__q_0.7',
        'intensity__minimum',
        'intensity__large_standard_deviation__r_0.15000000000000002',
        'intensity__quantile__q_0.1',
        'intensity__quantile__q_0.2',
        'intensity__fft_coefficient__attr_"real"__coeff_9',
        'intensity__cwt_coefficients__coeff_7__w_10__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_8__w_10__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_2__w_5__widths_(2, 5, 10, 20)',
        'intensity__quantile__q_0.3',
        'intensity__cwt_coefficients__coeff_9__w_10__widths_(2, 5, 10, 20)',
        'intensity__quantile__q_0.4',
        'intensity__cwt_coefficients__coeff_6__w_10__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_2__w_2__widths_(2, 5, 10, 20)',
        'intensity__range_count__max_1000000000000.0__min_0',
        'intensity__count_above__t_0',
        'intensity__count_below__t_0',
        'intensity__cwt_coefficients__coeff_8__w_5__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_10__w_10__widths_(2, 5, 10, 20)',
        'intensity__ratio_beyond_r_sigma__r_5',
        'intensity__median',
        'intensity__cwt_coefficients__coeff_5__w_10__widths_(2, 5, 10, 20)',
        'intensity__number_crossing_m__m_0',
        'intensity__number_crossing_m__m_1',
        'intensity__number_crossing_m__m_-1',
        'intensity__fft_coefficient__attr_"imag"__coeff_21',
        'intensity__cwt_coefficients__coeff_11__w_10__widths_(2, 5, 10, 20)',
        'intensity__quantile__q_0.6',
        'intensity__cwt_coefficients__coeff_4__w_10__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_3__w_2__widths_(2, 5, 10, 20)',
        'intensity__ar_coefficient__coeff_5__k_10',
        'intensity__cwt_coefficients__coeff_12__w_10__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"angle"__coeff_11',
        'intensity__first_location_of_minimum',
        'intensity__range_count__max_1__min_-1',
        'intensity__last_location_of_minimum',
        'intensity__quantile__q_0.7',
        'intensity__fft_coefficient__attr_"angle"__coeff_21',
        'intensity__cwt_coefficients__coeff_9__w_5__widths_(2, 5, 10, 20)',
        'intensity__number_peaks__n_50',
        'intensity__cwt_coefficients__coeff_3__w_10__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_13__w_10__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"real"__coeff_61',
        'intensity__change_quantiles__f_agg_"mean"__isabs_True__qh_0.4__ql_0.2',
        'intensity__value_count__value_1',
        'intensity__partial_autocorrelation__lag_9',
        'intensity__fft_coefficient__attr_"real"__coeff_51',
        'intensity__fft_coefficient__attr_"imag"__coeff_18',
        'intensity__cwt_coefficients__coeff_0__w_20__widths_(2, 5, 10, 20)',
        'intensity__ratio_beyond_r_sigma__r_1.5',
        'intensity__cwt_coefficients__coeff_14__w_10__widths_(2, 5, 10, 20)',
        'intensity__change_quantiles__f_agg_"var"__isabs_False__qh_0.4__ql_0.2',
        'intensity__fft_coefficient__attr_"angle"__coeff_18',
        'intensity__cwt_coefficients__coeff_1__w_5__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"real"__coeff_8',
        'intensity__fft_coefficient__attr_"real"__coeff_22',
        'intensity__fft_coefficient__attr_"imag"__coeff_2',
        'intensity__fft_coefficient__attr_"imag"__coeff_22',
        'intensity__friedrich_coefficients__coeff_2__m_3__r_30',
        'intensity__cwt_coefficients__coeff_1__w_20__widths_(2, 5, 10, 20)',
        'intensity__cwt_coefficients__coeff_1__w_2__widths_(2, 5, 10, 20)',
        'intensity__value_count__value_-1',
        'intensity__agg_autocorrelation__f_agg_"median"__maxlag_40',
        'intensity__fft_coefficient__attr_"real"__coeff_50',
        'intensity__cwt_coefficients__coeff_2__w_20__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"imag"__coeff_62',
        'intensity__cwt_coefficients__coeff_3__w_20__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"real"__coeff_4',
        'intensity__fft_coefficient__attr_"angle"__coeff_13',
        'intensity__friedrich_coefficients__coeff_0__m_3__r_30',
        'intensity__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"max"',
        'intensity__cwt_coefficients__coeff_2__w_10__widths_(2, 5, 10, 20)',
        'intensity__fft_coefficient__attr_"real"__coeff_2',
        'intensity__quantile__q_0.8',
        'intensity__autocorrelation__lag_9',
        'intensity__fft_coefficient__attr_"real"__coeff_46',
        'intensity__number_cwt_peaks__n_1',
        # --- TODO: camaroさんの特徴量
        # 'peak_wave_length',
        # 'peak_intensity',
        # 'mean',
        # 'std',
        # 'skew',
        # 'kurtosis',
        # 'skew_10',
        # 'kurtosis_10',
        # 'mean_10',
        # 'std_10',
        # 'skew_15',
        # 'kurtosis_15',
        # 'mean_15',
        # 'std_15',
        # 'skew_20',
        # 'kurtosis_20',
        # 'mean_20',
        # 'std_20',
        # 'skew_25',
        # 'kurtosis_25',
        # 'mean_25',
        # 'std_25',
        # 'skew_30',
        # 'kurtosis_30',
        # 'mean_30',
        # 'std_30',
        # 'skew_50',
        # 'kurtosis_50',
        # 'mean_50',
        # 'std_50',
        # 'skew_100',
        # 'kurtosis_100',
        # 'mean_100',
        # 'std_100',
        # 'skew_150',
        # 'kurtosis_150',
        # 'mean_150',
        # 'std_150',
        # 'skew_200',
        # 'kurtosis_200',
        # 'mean_200',
        # 'std_200',
        # 'em_ev',
        # 'ex_ev',
        # 'ev_diff',
        # 'ev_ratio',
        # 'num_peak',
        # 'num_strong_peak',
        # 'peak_wave_length2',
        # 'peak_intensity2',
        # 'peak_ratio',
        # 'peak_ratio2'
    ]

    try:
        # インスタンス生成
        runner = atm5_Runner(run_name, atm5_ModelLGB, features, setting, model_params, cv,
                             FEATURE_DIR_NAME, MODEL_DIR_NAME)
        use_feature_name = runner.get_feature_name()  # 今回の学習で使用する特徴量名を取得

        # モデルのconfigをjsonで保存
        value_list = [use_feature_name, model_params, cv, setting]
        save_model_config(key_list, value_list, dir_name, run_name)

        runner.run_train_cv()  # 学習
        runner.run_predict_cv()  # 推論

        Submission.create_submission(run_name, dir_name, setting.get('target'))  # submit作成

        # feature_importanceを計算
        atm5_ModelLGB.calc_feature_importance(dir_name, run_name, use_feature_name, cv.get('n_splits'), type='gain')

    except Exception as e:
        print(traceback.format_exc())
        print(f'ERROR:{e}')


if __name__ == '__main__':
    fire.Fire(main)
